/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);
var import_obsidian12 = require("obsidian");

// src/modals/FileShareModal.ts
var import_obsidian = require("obsidian");
var FileShareModal = class extends import_obsidian.SuggestModal {
  constructor(plugin, socket, friends, file = null, folder = null) {
    super(plugin.app);
    this.plugin = plugin;
    this.socket = socket;
    this.file = file;
    this.folder = folder;
    this.friends = friends;
  }
  getSuggestions(query) {
    return this.friends.filter(
      (friend) => friend.username.toLowerCase().includes(query.toLowerCase())
    );
  }
  renderSuggestion(friend, el) {
    el.createEl("div", { text: friend.username });
  }
  onChooseSuggestion(friend, evt) {
    this.checkOnlineAndSendFile(friend);
  }
  async checkOnlineAndSendFile(friend) {
    if (this.socket.getWS().readyState !== WebSocket.OPEN) {
      new import_obsidian.Notice("You are not connected to the FileShare server. Please connect first.");
      return;
    }
    if (this.file != null) {
      const validation = await this.plugin.fileValidator.validateFile(this.file);
      if (!validation.valid) {
        this.plugin.fileValidator.showValidationError(validation.error || "Invalid file");
        return;
      }
    }
    this.socket.send("checkOnline", { target: friend.publicKey });
    this.socket.getWS().onmessage = (message) => {
      const data = JSON.parse(message.data);
      if (data.type === "checkOnline" && data.target === friend.publicKey) {
        if (data.online) {
          if (this.file != null) {
            this.plugin.fileRequestQueue.addRequest(this.file, friend);
            if (this.plugin.settings.scanSendingFiles) {
              this.plugin.fileTransmitter.scanFileAndSend(this.file, friend);
            }
          } else if (this.folder != null) {
            this.sendFolderFiles(this.folder, friend);
          }
        } else {
          new import_obsidian.Notice(`${friend.username} is offline at the moment`);
        }
      } else if (data.type === "response") {
        this.plugin.fileRequestQueue.handleResponse(data.id, data.accepted, data.hash);
      }
    };
  }
  async sendFolderFiles(folder, friend) {
    const files = this.getAllFilesInFolder(folder);
    if (files.length === 0) {
      new import_obsidian.Notice("No files found in folder");
      return;
    }
    let validFileCount = 0;
    let invalidFileCount = 0;
    for (const file of files) {
      const validation = await this.plugin.fileValidator.validateFile(file);
      if (validation.valid) {
        const relativePath = this.getRelativePath(folder, file);
        this.plugin.fileRequestQueue.addRequest(file, friend, relativePath);
        if (this.plugin.settings.scanSendingFiles) {
          await this.plugin.fileTransmitter.scanFileAndSend(file, friend, relativePath);
        }
        validFileCount++;
      } else {
        console.log(`Skipping invalid file: ${file.name} - ${validation.error}`);
        invalidFileCount++;
      }
    }
    if (validFileCount > 0) {
      new import_obsidian.Notice(`Sending ${validFileCount} file(s) from folder "${folder.name}" to ${friend.username}`);
    }
    if (invalidFileCount > 0) {
      new import_obsidian.Notice(`Skipped ${invalidFileCount} invalid file(s)`);
    }
  }
  getRelativePath(baseFolder, file) {
    const basePath = baseFolder.path;
    const filePath = file.parent ? file.parent.path : "";
    if (filePath.startsWith(basePath)) {
      const relative = filePath.substring(basePath.length);
      return relative.startsWith("/") ? relative.substring(1) : relative;
    }
    return "";
  }
  getAllFilesInFolder(folder) {
    const files = [];
    const processFolder = (currentFolder) => {
      for (const child of currentFolder.children) {
        if (child instanceof import_obsidian.TFile) {
          files.push(child);
        } else if (child instanceof import_obsidian.TFolder) {
          processFolder(child);
        }
      }
    };
    processFolder(folder);
    return files;
  }
};

// src/settings/FileShareSettingTab.ts
var import_obsidian3 = require("obsidian");

// src/modals/FriendModal.ts
var import_obsidian2 = require("obsidian");
var FriendModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, index, fileShareSettingTab) {
    super(app);
    this.plugin = plugin;
    this.index = index;
    this.fileShareSettingTab = fileShareSettingTab;
    this.loadModalForm();
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", {
      text: this.index === null ? "Add Friend" : "Edit Friend"
    });
    new import_obsidian2.Setting(contentEl).setName("Username").addText((text) => {
      text.setValue(this.username);
      text.onChange((value) => {
        this.username = value;
      });
    });
    new import_obsidian2.Setting(contentEl).setName("Key").addText((text) => {
      text.setValue(this.publicKey);
      text.onChange((value) => {
        this.publicKey = value;
      });
    });
    new import_obsidian2.Setting(contentEl).setName("Enable hotkey").setDesc(
      "Enable a direct send command for this friend. After enabling, you can assign a hotkey in Obsidian's hotkey settings."
    ).addToggle((toggle) => {
      toggle.setValue(this.enableHotkey);
      toggle.onChange((value) => {
        this.enableHotkey = value;
      });
    });
    new import_obsidian2.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Save").setCta().onClick(() => {
        this.saveFriend();
      })
    );
  }
  saveFriend() {
    const username = this.username;
    const publicKey = this.publicKey;
    const enableHotkey = this.enableHotkey;
    if (username.length == 0 || publicKey.length == 0) {
      new import_obsidian2.Notice("Please fill out all fields.");
      return;
    } else if (this.plugin.settings.friends.filter((_, idx) => this.index == null || this.index != idx).some((friend) => friend.username === username)) {
      new import_obsidian2.Notice("A friend with this username is already set.");
      return;
    }
    const friendData = {
      username,
      publicKey,
      ...enableHotkey ? { enableHotkey: true } : {}
    };
    if (this.index === null) {
      this.plugin.settings.friends.push(friendData);
    } else {
      this.plugin.settings.friends[this.index] = friendData;
    }
    this.plugin.saveSettings();
    this.plugin.registerFriendCommands();
    this.close();
    this.fileShareSettingTab.display();
  }
  loadModalForm() {
    this.username = "";
    this.publicKey = "";
    this.enableHotkey = false;
    if (this.index !== null) {
      const friend = this.plugin.settings.friends[this.index];
      this.username = friend.username;
      this.publicKey = friend.publicKey;
      this.enableHotkey = friend.enableHotkey || false;
    }
  }
};

// src/settings/FileShareSettingTab.ts
var DEFAULT_SETTINGS = {
  useCustomSocketUrl: false,
  socketUrl: "wss://ws-fileshare.asss.ist",
  friends: [],
  receiveFolder: "/",
  privateKey: "",
  publicKey: "",
  autoAcceptFiles: false,
  scanSendingFiles: false,
  chunkSize: 262144,
  // 256KB in bytes
  maxFileSize: 524288e3,
  // 500MB in bytes
  lastSeenVersion: "0.0.0",
  preserveFolderStructure: true
};
var FileShareSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Your key").setDesc("This is your key. Share it with your friends.").addText((text) => {
      text.setValue(this.plugin.settings.publicKey).setDisabled(true);
    }).addExtraButton(
      (button) => button.setIcon("copy").setTooltip("Copy to clipboard").onClick(() => {
        navigator.clipboard.writeText(
          this.plugin.settings.publicKey
        );
        new import_obsidian3.Notice("Key copied to clipboard");
      })
    ).addExtraButton(
      (button) => button.setIcon("reset").setTooltip("Generate new key pair").onClick(async () => {
        const confirmation = confirm(
          "Are you sure you want to generate a new key pair? Your current key will be lost."
        );
        if (confirmation) {
          const { privateKey, publicKey } = await this.plugin.secure.generateKeyPair();
          this.plugin.settings.privateKey = privateKey;
          this.plugin.settings.publicKey = publicKey;
          await this.plugin.saveSettings();
          this.display();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Receive folder").setDesc("Select the folder where received files will be saved.").addDropdown((drop) => {
      const folders = this.plugin.app.vault.getAllLoadedFiles().filter((file) => file instanceof import_obsidian3.TFolder);
      folders.forEach((folder) => {
        const displayName = folder.path.length > 40 ? folder.path.substring(0, 37) + "..." : folder.path;
        drop.addOption(folder.path, displayName);
      });
      drop.setValue(this.plugin.settings.receiveFolder);
      drop.onChange(async (value) => {
        this.plugin.settings.receiveFolder = value;
        await this.plugin.saveSettings();
      });
      drop.selectEl.addClass("file-share-receive-folder-dropdown");
    });
    new import_obsidian3.Setting(containerEl).setName("Scan files for first-level embedded links").setDesc(
      "Enhance the ability to automatically scan your outgoing file for first-level embedded links to other documents or images, ensuring they are transmitted alongside the corresponding attachments."
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.scanSendingFiles).onChange(async (value) => {
        this.plugin.settings.scanSendingFiles = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Preserve folder structure").setDesc(
      "When receiving files that were sent from a folder, recreate the folder structure in your receive folder. If disabled, all files will be saved directly to the receive folder."
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.preserveFolderStructure).onChange(async (value) => {
        this.plugin.settings.preserveFolderStructure = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Need any help?").setDesc(
      "Feel free to explore the documentation for comprehensive guidance and support."
    ).addButton(
      (button) => button.setButtonText("Open documentation").setCta().onClick(
        () => window.open(
          "https://muckmuck96.github.io/obsidian-file-share/",
          "_blank"
        )
      )
    );
    new import_obsidian3.Setting(containerEl).setName("Add Friend").addButton(
      (button) => button.setButtonText("Add").onClick(() => this.addFriend())
    );
    this.plugin.settings.friends.forEach((friend, index) => {
      const hotkeyId = this.plugin.generateHotkeyId(friend.username);
      const friendDescription = friend.enableHotkey ? `Hotkey enabled (Command ID: ${hotkeyId})` : "No hotkey";
      const setting = new import_obsidian3.Setting(containerEl).setName(`Username: ${friend.username}`).setDesc(friendDescription).addToggle(
        (toggle) => toggle.setTooltip("Enable hotkey").setValue(friend.enableHotkey || false).onChange(async (value) => {
          friend.enableHotkey = value;
          await this.plugin.saveSettings();
          this.plugin.registerFriendCommands();
          this.display();
        })
      ).addButton(
        (button) => button.setButtonText("Edit").onClick(() => this.editFriend(index))
      ).addButton(
        (button) => button.setButtonText("Delete").onClick(() => {
          this.plugin.settings.friends.splice(index, 1);
          this.plugin.saveSettings();
          this.plugin.registerFriendCommands();
          this.display();
        })
      );
      if (friend.enableHotkey) {
        setting.addExtraButton(
          (button) => button.setIcon("settings").setTooltip("Open hotkey settings").onClick(() => {
            this.app.setting.open();
            this.app.setting.openTabById("hotkeys");
          })
        );
      }
    });
    containerEl.createEl("hr");
    const advancedSettingsHeader = new import_obsidian3.Setting(containerEl).setName("Advanced Settings").setDesc(
      "\u26A0\uFE0F Only change these settings if you know what you are doing."
    ).setHeading();
    const advancedSettingsContent = containerEl.createDiv();
    advancedSettingsContent.style.display = "none";
    advancedSettingsHeader.addToggle(
      (toggle) => toggle.setValue(false).setTooltip("Show/hide advanced settings").onChange((value) => {
        advancedSettingsContent.style.display = value ? "block" : "none";
      })
    );
    new import_obsidian3.Setting(advancedSettingsContent).setName("Chunk size (KB)").setDesc(
      "Size of each chunk when sending files. Smaller chunks are more reliable for unstable connections, larger chunks are faster. Range: 64KB - 1024KB (1MB)."
    ).addSlider((slider) => {
      slider.setLimits(64, 1024, 64).setValue(this.plugin.settings.chunkSize / 1024).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.chunkSize = value * 1024;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(advancedSettingsContent).setName("Auto-accept incoming files").setDesc(
      "Enable to automatically accept incoming files. Attention: There is a potential security risk to do that."
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.autoAcceptFiles).onChange(async (value) => {
        let confirmation = true;
        if (!this.plugin.settings.autoAcceptFiles && value) {
          confirmation = confirm(
            "Are you sure you want to activate this option?."
          );
        }
        if (confirmation) {
          this.plugin.settings.autoAcceptFiles = value;
          await this.plugin.saveSettings();
        }
        this.display();
      });
    });
    new import_obsidian3.Setting(advancedSettingsContent).setName("Socket URL").setDesc(
      "Socket URL to exchange files end-to-end encrypted. Only SSL supported."
    ).addToggle(
      (toggle) => toggle.setTooltip("Use custom").setValue(this.plugin.settings.useCustomSocketUrl).onChange(async (value) => {
        if (!value) {
          this.plugin.settings.socketUrl = this.plugin.getDefaultSettings().socketUrl;
        }
        this.plugin.settings.useCustomSocketUrl = value;
        await this.plugin.saveSettings();
        this.display();
      })
    ).addText((text) => {
      text.setPlaceholder("").setValue(this.plugin.settings.socketUrl).setDisabled(!this.plugin.settings.useCustomSocketUrl).onChange(async (value) => {
        this.plugin.settings.socketUrl = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.addEventListener("blur", async () => {
        if (this.plugin.settings.useCustomSocketUrl && !this.plugin.secure.isSocketURLSecure()) {
          new import_obsidian3.Notice(
            "Socket URL could not be validated for SSL. Reverting to default socket server..."
          );
          this.plugin.settings.socketUrl = this.plugin.getDefaultSettings().socketUrl;
          this.plugin.settings.useCustomSocketUrl = false;
          await this.plugin.saveSettings();
          this.display();
        }
      });
    });
  }
  addFriend() {
    const modal = new FriendModal(this.app, this.plugin, null, this);
    modal.open();
  }
  editFriend(index) {
    const modal = new FriendModal(this.app, this.plugin, index, this);
    modal.open();
  }
};

// src/security/Secure.ts
var crypto2 = __toESM(require("crypto"));
var import_obsidian4 = require("obsidian");
var Secure = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async generateKeyPair() {
    const { privateKey, publicKey } = crypto2.generateKeyPairSync("rsa", {
      modulusLength: 2048
    });
    return {
      privateKey: privateKey.export({ type: "pkcs1", format: "pem" }).toString(),
      publicKey: Buffer.from(
        publicKey.export({ type: "pkcs1", format: "pem" }).toString()
      ).toString("base64")
    };
  }
  serializePublicKey(publicKey) {
    return Buffer.from(publicKey, "base64").toString();
  }
  async verifySignature(decryptedFile, receivedSignature, publicKey) {
    const verify = crypto2.createVerify("SHA256");
    verify.update(decryptedFile);
    const verified = verify.verify(
      crypto2.createPublicKey(publicKey),
      receivedSignature,
      "base64"
    );
    return verified;
  }
  async decryptFile(encryptedAesKey, iv, encryptedFile) {
    const aesKey = crypto2.privateDecrypt(
      crypto2.createPrivateKey(this.plugin.settings.privateKey),
      encryptedAesKey
    );
    const decipher = crypto2.createDecipheriv("aes-256-cbc", aesKey, iv);
    return Buffer.concat([
      decipher.update(encryptedFile),
      decipher.final()
    ]);
  }
  generateHash(data) {
    const hmac = crypto2.createHmac(
      "sha256",
      this.plugin.settings.privateKey
    );
    hmac.update(`${data.filename}${data.from}`);
    return hmac.digest("base64");
  }
  async signFile(file) {
    if (!file) {
      new import_obsidian4.Notice("No file selected");
      return null;
    }
    const fileContent = await this.plugin.app.vault.readBinary(file);
    const sign = crypto2.createSign("SHA256");
    sign.update(Buffer.from(fileContent));
    const signature = sign.sign(this.plugin.settings.privateKey, "base64");
    return signature;
  }
  signData(data) {
    const sign = crypto2.createHmac(
      "SHA256",
      this.plugin.settings.privateKey
    );
    sign.update(data);
    return sign.digest("base64");
  }
  async encryptFile(file, friend) {
    if (!file) {
      new import_obsidian4.Notice("No file selected");
      return null;
    }
    const signature = await this.signFile(file);
    const publicKey = this.plugin.secure.serializePublicKey(
      friend.publicKey
    );
    const fileContent = await this.plugin.app.vault.readBinary(file);
    const aesKey = crypto2.randomBytes(32);
    const iv = crypto2.randomBytes(16);
    const cipher = crypto2.createCipheriv("aes-256-cbc", aesKey, iv);
    const encryptedFile = Buffer.concat([
      cipher.update(Buffer.from(fileContent)),
      cipher.final()
    ]);
    const encryptedAesKey = crypto2.publicEncrypt(publicKey, aesKey);
    return {
      file: encryptedFile.toString("base64"),
      aesKey: encryptedAesKey.toString("base64"),
      iv: iv.toString("base64"),
      filename: file.name,
      signature
    };
  }
  isSocketURLSecure() {
    return true;
  }
  async encryptFileChunked(file, friend) {
    if (!file) {
      new import_obsidian4.Notice("No file selected");
      return null;
    }
    const fileContent = await this.plugin.app.vault.readBinary(file);
    const fileId = crypto2.randomUUID();
    const chunkSize = this.plugin.settings.chunkSize;
    const totalChunks = Math.ceil(fileContent.byteLength / chunkSize);
    const aesKey = crypto2.randomBytes(32);
    const iv = crypto2.randomBytes(16);
    const signature = await this.signFile(file);
    if (!signature) {
      return null;
    }
    const publicKey = this.serializePublicKey(friend.publicKey);
    const encryptedAesKey = crypto2.publicEncrypt(publicKey, aesKey);
    const chunks = [];
    for (let i = 0; i < totalChunks; i++) {
      const start = i * chunkSize;
      const end = Math.min(start + chunkSize, fileContent.byteLength);
      const chunkData = Buffer.from(fileContent.slice(start, end));
      const cipher = crypto2.createCipheriv("aes-256-cbc", aesKey, iv);
      const encryptedChunk = Buffer.concat([
        cipher.update(chunkData),
        cipher.final()
      ]);
      chunks.push({
        chunkIndex: i,
        totalChunks,
        chunkData: encryptedChunk.toString("base64"),
        aesKey: encryptedAesKey.toString("base64"),
        iv: iv.toString("base64"),
        filename: file.name,
        fileId,
        signature
      });
    }
    const metadata = {
      fileId,
      filename: file.name,
      totalChunks,
      totalSize: fileContent.byteLength,
      sender: this.plugin.settings.publicKey
    };
    return { metadata, chunks };
  }
  async decryptChunk(encryptedAesKey, iv, encryptedChunk) {
    const aesKey = crypto2.privateDecrypt(
      crypto2.createPrivateKey(this.plugin.settings.privateKey),
      encryptedAesKey
    );
    const decipher = crypto2.createDecipheriv("aes-256-cbc", aesKey, iv);
    return Buffer.concat([
      decipher.update(encryptedChunk),
      decipher.final()
    ]);
  }
};

// src/core/Socket.ts
var import_obsidian5 = require("obsidian");
var Socket = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.setConnectionStatus("disconnected");
  }
  close() {
    this.ws.close();
  }
  send(type, data) {
    if (this.ws.readyState !== WebSocket.OPEN) {
      new import_obsidian5.Notice("Cannot send message: Not connected to FileShare server.");
      console.error("WebSocket is not open. ReadyState:", this.ws.readyState);
      return;
    }
    const payload = Object.assign({ type }, data);
    this.ws.send(JSON.stringify(payload));
  }
  getWS() {
    return this.ws;
  }
  setConnectionStatus(connectionStatus) {
    this.plugin.connectionStatus.innerText = `FileShare: ${connectionStatus}`;
  }
  async verifySocketURL() {
    if (!this.plugin.secure.isSocketURLSecure()) {
      new import_obsidian5.Notice(
        "Socket URL could not be validated for SSL. Using default socket server..."
      );
      this.plugin.settings.socketUrl = this.plugin.getDefaultSettings().socketUrl;
      this.plugin.settings.useCustomSocketUrl = false;
      await this.plugin.saveSettings();
    }
  }
  toggleConnection() {
    if (this.ws.readyState === WebSocket.OPEN) {
      this.ws.close();
      new import_obsidian5.Notice("Closing connection...");
    } else if (this.ws.readyState !== WebSocket.OPEN) {
      this.init();
      new import_obsidian5.Notice("Trying to connect...");
    }
  }
  async init() {
    await this.verifySocketURL();
    this.ws = new WebSocket(this.plugin.settings.socketUrl);
    this.ws.onopen = () => {
      new import_obsidian5.Notice("FileShare connection opened.");
      this.setConnectionStatus("connected");
      this.send("login", { name: this.plugin.settings.publicKey || "" });
    };
    this.ws.onmessage = (message) => {
      const data = JSON.parse(message.data);
      if (data.sender && this.plugin.settings.friends.some(
        (friend) => friend.publicKey === data.sender
      )) {
        const sender = this.plugin.settings.friends.find(
          (friend) => friend.publicKey == data.sender
        );
        if (data.type == "file") {
          const expectedHash = this.plugin.secure.generateHash(data);
          if (data.hash === expectedHash) {
            this.plugin.fileTransmitter.receiveFile(data);
          }
        } else if (data.type == "fileMetadata") {
          this.plugin.fileTransmitter.receiveFileMetadata(data.payload);
        } else if (data.type == "fileChunk") {
          this.plugin.fileTransmitter.receiveFileChunk(data.payload);
        } else if (data.type == "request") {
          const accept = this.plugin.settings.autoAcceptFiles || confirm(
            `${sender == null ? void 0 : sender.username} want to sent you: ${data.filename}. Accept it?`
          );
          const hash = accept ? this.plugin.secure.generateHash(data) : "";
          this.send("response", {
            target: data.sender,
            accepted: accept,
            filename: data.filename,
            hash,
            id: data.id
          });
        }
      }
    };
    this.ws.onclose = () => {
      this.setConnectionStatus("disconnected");
      new import_obsidian5.Notice("FileShare connection closed.");
    };
    this.ws.onerror = (error) => {
      console.error("WebSocket error:", error);
      new import_obsidian5.Notice("WebSocket error occurred. Check console for details.");
    };
  }
};

// src/core/FileTransmitter.ts
var import_obsidian6 = require("obsidian");
var FileTransmitter = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.activeTransfers = /* @__PURE__ */ new Map();
    this.receivingFiles = /* @__PURE__ */ new Map();
  }
  async sendFile(file, friend, hash, sourceFolderPath) {
    if (!file) {
      new import_obsidian6.Notice("No file selected");
      return;
    }
    const fileStats = await this.plugin.app.vault.adapter.stat(file.path);
    if (!fileStats) {
      new import_obsidian6.Notice("Could not read file");
      return;
    }
    if (fileStats.size > this.plugin.settings.chunkSize) {
      await this.sendFileChunked(file, friend, hash, sourceFolderPath);
    } else {
      const encryptedFilePayload = await this.plugin.secure.encryptFile(
        file,
        friend
      );
      const payload = Object.assign(
        { sender: this.plugin.settings.publicKey },
        encryptedFilePayload
      );
      this.plugin.socket.send("file", {
        payload,
        target: friend.publicKey,
        hash,
        sourceFolderPath
      });
      new import_obsidian6.Notice(`File sent to ${friend.username}`);
    }
  }
  async sendFileChunked(file, friend, hash, sourceFolderPath) {
    const result = await this.plugin.secure.encryptFileChunked(file, friend);
    if (!result) {
      new import_obsidian6.Notice("Failed to encrypt file");
      return;
    }
    const { metadata, chunks } = result;
    this.activeTransfers.set(metadata.fileId, {
      currentChunk: 0,
      totalChunks: metadata.totalChunks
    });
    this.plugin.socket.send("fileMetadata", {
      payload: metadata,
      target: friend.publicKey,
      hash,
      sourceFolderPath
    });
    for (let i = 0; i < chunks.length; i++) {
      const chunk = chunks[i];
      this.plugin.socket.send("fileChunk", {
        payload: chunk,
        target: friend.publicKey,
        hash,
        sourceFolderPath
      });
      this.activeTransfers.set(metadata.fileId, {
        currentChunk: i + 1,
        totalChunks: metadata.totalChunks
      });
      if (i < chunks.length - 1) {
        await new Promise((resolve) => setTimeout(resolve, 10));
      }
    }
    new import_obsidian6.Notice(`File sent to ${friend.username} in ${chunks.length} chunks`);
    this.activeTransfers.delete(metadata.fileId);
  }
  getTransferProgress(fileId) {
    return this.activeTransfers.get(fileId);
  }
  async receiveFile(data) {
    if (!data.sender) {
      new import_obsidian6.Notice("Sender not found");
      return;
    }
    const filePath = this.constructReceivePath(data.filename, data.sourceFolderPath);
    const encryptedFile = Buffer.from(data.file, "base64");
    const encryptedAesKey = Buffer.from(data.aesKey, "base64");
    const iv = Buffer.from(data.iv, "base64");
    const decryptedFile = await this.plugin.secure.decryptFile(
      encryptedAesKey,
      iv,
      encryptedFile
    );
    const isVerified = await this.plugin.secure.verifySignature(
      decryptedFile,
      data.signature,
      this.plugin.secure.serializePublicKey(data.sender)
    );
    if (!isVerified) {
      new import_obsidian6.Notice("Signature verification failed. File not saved.");
      return;
    }
    try {
      await this.ensureFolderExists(filePath);
      await this.plugin.app.vault.createBinary(filePath, decryptedFile);
      new import_obsidian6.Notice(`File received and saved to ${filePath}`);
    } catch (error) {
      console.error("Error saving received file:", error);
      new import_obsidian6.Notice("Failed to save the received file.");
    }
  }
  constructReceivePath(filename, sourceFolderPath) {
    const receiveFolder = this.plugin.settings.receiveFolder;
    if (this.plugin.settings.preserveFolderStructure && sourceFolderPath) {
      const fullPath = `${receiveFolder}/${sourceFolderPath}/${filename}`;
      return fullPath.replace(/\/+/g, "/");
    }
    return `${receiveFolder}/${filename}`;
  }
  async ensureFolderExists(filePath) {
    const parts = filePath.split("/");
    parts.pop();
    const folderPath = parts.join("/");
    const folder = this.plugin.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      try {
        await this.plugin.app.vault.createFolder(folderPath);
      } catch (error) {
        console.log(`Folder creation note: ${error}`);
      }
    }
  }
  async scanFileAndSend(file, friend, sourceFolderPath) {
    const content = await this.plugin.app.vault.read(file);
    const links = content.match(/\[\[(.*?)\]\]/g);
    if (!links) {
      return;
    }
    for (const link of links) {
      const fileName = link.replace(/\[\[(.*?)\]\]/g, "$1");
      const linkedFile = this.plugin.app.metadataCache.getFirstLinkpathDest(
        fileName,
        file.path
      );
      if (linkedFile) {
        const validation = await this.plugin.fileValidator.validateFile(linkedFile);
        if (validation.valid) {
          this.plugin.fileRequestQueue.addRequest(linkedFile, friend);
        } else {
          console.log(`Skipping invalid linked file: ${linkedFile.name} - ${validation.error}`);
        }
      }
    }
  }
  async receiveFileMetadata(data) {
    if (!data.sender) {
      new import_obsidian6.Notice("Sender not found");
      return;
    }
    this.receivingFiles.set(data.fileId, {
      fileId: data.fileId,
      filename: data.filename,
      totalChunks: data.totalChunks,
      receivedChunks: 0,
      chunks: /* @__PURE__ */ new Map(),
      sender: data.sender,
      sourceFolderPath: data.sourceFolderPath
    });
    new import_obsidian6.Notice(`Receiving file: ${data.filename} (${data.totalChunks} chunks)`);
  }
  async receiveFileChunk(data) {
    const fileProgress = this.receivingFiles.get(data.fileId);
    if (!fileProgress) {
      new import_obsidian6.Notice("Received chunk for unknown file");
      return;
    }
    const encryptedChunk = Buffer.from(data.chunkData, "base64");
    const encryptedAesKey = Buffer.from(data.aesKey, "base64");
    const iv = Buffer.from(data.iv, "base64");
    const decryptedChunk = await this.plugin.secure.decryptChunk(
      encryptedAesKey,
      iv,
      encryptedChunk
    );
    fileProgress.chunks.set(data.chunkIndex, decryptedChunk);
    fileProgress.receivedChunks++;
    if (!fileProgress.signature) {
      fileProgress.signature = data.signature;
    }
    if (fileProgress.receivedChunks === fileProgress.totalChunks) {
      await this.reassembleFile(fileProgress);
    }
  }
  async reassembleFile(fileProgress) {
    const chunks = [];
    for (let i = 0; i < fileProgress.totalChunks; i++) {
      const chunk = fileProgress.chunks.get(i);
      if (!chunk) {
        new import_obsidian6.Notice(`Missing chunk ${i} for file ${fileProgress.filename}`);
        this.receivingFiles.delete(fileProgress.fileId);
        return;
      }
      chunks.push(chunk);
    }
    const completeFile = Buffer.concat(chunks);
    if (fileProgress.signature && fileProgress.sender) {
      const isVerified = await this.plugin.secure.verifySignature(
        completeFile,
        fileProgress.signature,
        this.plugin.secure.serializePublicKey(fileProgress.sender)
      );
      if (!isVerified) {
        new import_obsidian6.Notice("Signature verification failed. File not saved.");
        this.receivingFiles.delete(fileProgress.fileId);
        return;
      }
    }
    const filePath = this.constructReceivePath(fileProgress.filename, fileProgress.sourceFolderPath);
    try {
      await this.ensureFolderExists(filePath);
      await this.plugin.app.vault.createBinary(filePath, completeFile);
      new import_obsidian6.Notice(`File received and saved to ${filePath}`);
    } catch (error) {
      console.error("Error saving received file:", error);
      new import_obsidian6.Notice("Failed to save the received file.");
    }
    this.receivingFiles.delete(fileProgress.fileId);
  }
  getReceivingProgress(fileId) {
    return this.receivingFiles.get(fileId);
  }
};

// src/core/FileRequestQueue.ts
var import_obsidian7 = require("obsidian");
var FileRequestQueue = class {
  constructor(sendFileMethod, plugin) {
    this.queue = /* @__PURE__ */ new Map();
    this.sendFileMethod = sendFileMethod;
    this.plugin = plugin;
  }
  addRequest(file, recipient, sourceFolderPath) {
    const requestId = this.generateRequestId();
    const request = {
      id: requestId,
      file,
      recipient,
      state: "pending",
      progress: 0,
      sourceFolderPath
    };
    this.queue.set(requestId, request);
    this.sendIFileRequest(request);
  }
  updateRequestState(requestId, state, progress) {
    const request = this.queue.get(requestId);
    if (request) {
      request.state = state;
      if (progress !== void 0) {
        request.progress = progress;
      }
      this.queue.set(requestId, request);
    }
  }
  getRequestByFileId(fileId) {
    for (const request of this.queue.values()) {
      if (request.fileId === fileId) {
        return request;
      }
    }
    return void 0;
  }
  getRequestsByFile(file) {
    const requests = [];
    for (const request of this.queue.values()) {
      if (request.file.path === file.path) {
        requests.push(request);
      }
    }
    return requests;
  }
  handleResponse(requestId, accepted, hash) {
    const request = this.queue.get(requestId);
    if (request) {
      if (accepted) {
        this.updateRequestState(requestId, "accepted");
        new import_obsidian7.Notice(`File request accepted by ${request.recipient.username}`);
        this.sendFileMethod(request.file, request.recipient, hash, request.sourceFolderPath).then(() => {
          this.updateRequestState(requestId, "completed", 100);
          setTimeout(() => {
            this.queue.delete(requestId);
          }, 3e3);
        }).catch((error) => {
          console.error("Error sending the file:", error);
          this.updateRequestState(requestId, "failed");
          setTimeout(() => {
            this.queue.delete(requestId);
          }, 5e3);
        });
      } else {
        this.updateRequestState(requestId, "rejected");
        new import_obsidian7.Notice(`File request declined by ${request.recipient.username}`);
        setTimeout(() => {
          this.queue.delete(requestId);
        }, 3e3);
      }
    }
  }
  generateRequestId() {
    return crypto.randomUUID();
  }
  sendIFileRequest(request) {
    var _a, _b, _c;
    const requestData = JSON.stringify({
      type: "request",
      target: request.recipient.publicKey,
      filename: (_a = request.file) == null ? void 0 : _a.name,
      sourceFolderPath: request.sourceFolderPath
    });
    const dataSign = this.plugin.secure.signData(requestData);
    this.plugin.socket.send("request", {
      target: request.recipient.publicKey,
      filename: (_b = request.file) == null ? void 0 : _b.name,
      signature: dataSign,
      id: request.id,
      sourceFolderPath: request.sourceFolderPath
    });
    new import_obsidian7.Notice(
      `Request sent to ${request.recipient.username} for file ${(_c = request.file) == null ? void 0 : _c.name}`
    );
  }
};

// src/utils/FileValidator.ts
var import_obsidian8 = require("obsidian");
var _FileValidator = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async validateFile(file) {
    const typeValidation = this.validateFileType(file);
    if (!typeValidation.valid) {
      return typeValidation;
    }
    const sizeValidation = await this.validateFileSize(file);
    if (!sizeValidation.valid) {
      return sizeValidation;
    }
    return { valid: true };
  }
  validateFileType(file) {
    const extension = file.extension.toLowerCase();
    const allAllowedExtensions = [
      ..._FileValidator.ALLOWED_EXTENSIONS.markdown,
      ..._FileValidator.ALLOWED_EXTENSIONS.images,
      ..._FileValidator.ALLOWED_EXTENSIONS.videos,
      ..._FileValidator.ALLOWED_EXTENSIONS.audio,
      ..._FileValidator.ALLOWED_EXTENSIONS.documents,
      ..._FileValidator.ALLOWED_EXTENSIONS.obsidian,
      ..._FileValidator.ALLOWED_EXTENSIONS.data
    ].map((ext) => ext.substring(1));
    if (!allAllowedExtensions.includes(extension)) {
      return {
        valid: false,
        error: `File type ".${extension}" is not allowed. Supported types: markdown, images, videos, audio, documents (PDF, TXT), Obsidian files (canvas, excalidraw), and data files (JSON, CSV, etc.).`
      };
    }
    return { valid: true };
  }
  async validateFileSize(file) {
    const fileStats = await this.plugin.app.vault.adapter.stat(file.path);
    if (!fileStats) {
      return {
        valid: false,
        error: "Could not read file statistics"
      };
    }
    const fileSizeBytes = fileStats.size;
    const maxSizeBytes = this.plugin.settings.maxFileSize;
    if (fileSizeBytes > maxSizeBytes) {
      const fileSizeMB = (fileSizeBytes / (1024 * 1024)).toFixed(2);
      const maxSizeMB = (maxSizeBytes / (1024 * 1024)).toFixed(2);
      return {
        valid: false,
        error: `File size (${fileSizeMB} MB) exceeds maximum allowed size (${maxSizeMB} MB)`
      };
    }
    return { valid: true };
  }
  isVideoFile(file) {
    const extension = `.${file.extension.toLowerCase()}`;
    return _FileValidator.ALLOWED_EXTENSIONS.videos.includes(extension);
  }
  isImageFile(file) {
    const extension = `.${file.extension.toLowerCase()}`;
    return _FileValidator.ALLOWED_EXTENSIONS.images.includes(extension);
  }
  isMarkdownFile(file) {
    const extension = `.${file.extension.toLowerCase()}`;
    return _FileValidator.ALLOWED_EXTENSIONS.markdown.includes(extension);
  }
  showValidationError(error) {
    new import_obsidian8.Notice(error);
  }
};
var FileValidator = _FileValidator;
FileValidator.ALLOWED_EXTENSIONS = {
  markdown: [".md", ".markdown"],
  images: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".svg", ".webp", ".ico"],
  videos: [".mp4", ".webm", ".ogv", ".mov", ".avi", ".mkv"],
  audio: [".mp3", ".wav", ".ogg", ".m4a", ".flac", ".aac"],
  documents: [".pdf", ".txt", ".rtf"],
  obsidian: [".excalidraw", ".canvas"],
  data: [".json", ".csv", ".xml", ".yaml", ".yml"]
};
FileValidator.MAX_VIDEO_DURATION_SECONDS = 60;

// src/ui/FileTreeDecorator.ts
var import_obsidian9 = require("obsidian");
var FileTreeDecorator = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.decorations = /* @__PURE__ */ new Map();
    this.startUpdateLoop();
  }
  startUpdateLoop() {
    this.updateInterval = window.setInterval(() => {
      this.updateAllDecorations();
    }, 500);
  }
  cleanup() {
    if (this.updateInterval) {
      window.clearInterval(this.updateInterval);
    }
    this.clearAllDecorations();
  }
  updateAllDecorations() {
    const files = this.plugin.app.vault.getFiles();
    files.forEach((file) => {
      const requests = this.plugin.fileRequestQueue.getRequestsByFile(file);
      if (requests.length > 0) {
        const primaryRequest = requests[0];
        this.addOrUpdateDecoration(file.path, primaryRequest.state, primaryRequest.progress || 0);
      } else {
        this.removeDecoration(file.path);
      }
    });
    this.updateFolderDecorations();
  }
  updateFolderDecorations() {
    const allFolders = this.plugin.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian9.TFolder);
    allFolders.forEach((folder) => {
      const folderStatus = this.getFolderTransferStatus(folder);
      if (folderStatus) {
        this.addOrUpdateDecoration(folder.path, folderStatus.state, folderStatus.progress);
      } else {
        this.removeDecoration(folder.path);
      }
    });
  }
  getFolderTransferStatus(folder) {
    const filesInFolder = [];
    const getAllFiles = (currentFolder) => {
      for (const child of currentFolder.children) {
        if (child instanceof import_obsidian9.TFile) {
          filesInFolder.push(child);
        } else if (child instanceof import_obsidian9.TFolder) {
          getAllFiles(child);
        }
      }
    };
    getAllFiles(folder);
    if (filesInFolder.length === 0) {
      return null;
    }
    let totalFiles = 0;
    let pendingFiles = 0;
    let sendingFiles = 0;
    let completedFiles = 0;
    let failedFiles = 0;
    let totalProgress = 0;
    filesInFolder.forEach((file) => {
      const requests = this.plugin.fileRequestQueue.getRequestsByFile(file);
      if (requests.length > 0) {
        totalFiles++;
        const request = requests[0];
        switch (request.state) {
          case "pending":
          case "accepted":
            pendingFiles++;
            break;
          case "sending":
            sendingFiles++;
            totalProgress += request.progress || 0;
            break;
          case "completed":
            completedFiles++;
            totalProgress += 100;
            break;
          case "failed":
          case "rejected":
            failedFiles++;
            break;
        }
      }
    });
    if (totalFiles === 0) {
      return null;
    }
    if (failedFiles > 0) {
      return { state: "failed", progress: 0 };
    } else if (completedFiles === totalFiles) {
      return { state: "completed", progress: 100 };
    } else if (sendingFiles > 0) {
      const avgProgress = Math.round(totalProgress / totalFiles);
      return { state: "sending", progress: avgProgress };
    } else if (pendingFiles > 0) {
      return { state: "pending", progress: 0 };
    }
    return null;
  }
  addOrUpdateDecoration(path, state, progress) {
    const fileExplorer = this.getFileExplorer();
    if (!fileExplorer)
      return;
    const element = this.findFileOrFolderElement(path);
    if (!element)
      return;
    const existingDecoration = this.decorations.get(path);
    if (existingDecoration) {
      this.updateDecorationContent(existingDecoration, state, progress);
    } else {
      const decoration = this.createDecoration(state, progress);
      const titleElement = element.querySelector(".nav-file-title-content, .nav-folder-title-content");
      if (titleElement) {
        titleElement.appendChild(decoration);
        this.decorations.set(path, decoration);
      }
    }
  }
  createDecoration(state, progress) {
    const container = document.createElement("span");
    container.addClass("file-share-indicator");
    container.style.marginLeft = "5px";
    container.style.fontSize = "0.9em";
    this.updateDecorationContent(container, state, progress);
    return container;
  }
  updateDecorationContent(element, state, progress) {
    let icon = "";
    let color = "";
    let title = "";
    switch (state) {
      case "pending":
        icon = "\u23F3";
        color = "#888";
        title = "Waiting for response...";
        break;
      case "accepted":
        icon = "\u2713";
        color = "#4CAF50";
        title = "Request accepted";
        break;
      case "sending":
        icon = "\u{1F4E4}";
        color = "#2196F3";
        title = `Sending... ${progress}%`;
        break;
      case "completed":
        icon = "\u2705";
        color = "#4CAF50";
        title = "Transfer completed";
        break;
      case "failed":
        icon = "\u274C";
        color = "#F44336";
        title = "Transfer failed";
        break;
      case "rejected":
        icon = "\u{1F6AB}";
        color = "#FF9800";
        title = "Request rejected";
        break;
    }
    element.textContent = icon;
    element.style.color = color;
    element.title = title;
    if (state === "sending" && progress > 0) {
      element.textContent = `${icon} ${progress}%`;
    }
  }
  removeDecoration(path) {
    const decoration = this.decorations.get(path);
    if (decoration) {
      decoration.remove();
      this.decorations.delete(path);
    }
  }
  clearAllDecorations() {
    this.decorations.forEach((decoration) => {
      decoration.remove();
    });
    this.decorations.clear();
  }
  getFileExplorer() {
    const leaves = this.plugin.app.workspace.getLeavesOfType("file-explorer");
    if (leaves.length > 0) {
      return leaves[0].view;
    }
    return null;
  }
  findFileOrFolderElement(path) {
    const fileExplorer = this.getFileExplorer();
    if (!fileExplorer)
      return null;
    const fileItems = document.querySelectorAll(".nav-file");
    for (const item of Array.from(fileItems)) {
      const titleElement = item.querySelector(".nav-file-title");
      if (titleElement) {
        const dataPath = titleElement.getAttribute("data-path");
        if (dataPath === path) {
          return item;
        }
      }
    }
    const folderItems = document.querySelectorAll(".nav-folder");
    for (const item of Array.from(folderItems)) {
      const titleElement = item.querySelector(".nav-folder-title");
      if (titleElement) {
        const dataPath = titleElement.getAttribute("data-path");
        if (dataPath === path) {
          return item;
        }
      }
    }
    return null;
  }
};

// src/utils/ReleaseNotesManager.ts
var import_obsidian10 = require("obsidian");
var ReleaseNotesManager = class {
  static async fetchLatestRelease() {
    try {
      const response = await (0, import_obsidian10.requestUrl)({
        url: this.GITHUB_API_URL,
        method: "GET",
        headers: {
          "Accept": "application/vnd.github.v3+json"
        }
      });
      if (response.status === 200) {
        return response.json;
      } else {
        console.error("Failed to fetch release notes:", response.status);
        return null;
      }
    } catch (error) {
      console.error("Error fetching release notes:", error);
      new import_obsidian10.Notice("Failed to fetch release notes from GitHub.");
      return null;
    }
  }
  static compareVersions(currentVersion, latestVersion) {
    const current = currentVersion.replace(/^v/, "");
    const latest = latestVersion.replace(/^v/, "");
    const currentParts = current.split(".").map(Number);
    const latestParts = latest.split(".").map(Number);
    for (let i = 0; i < Math.max(currentParts.length, latestParts.length); i++) {
      const currentPart = currentParts[i] || 0;
      const latestPart = latestParts[i] || 0;
      if (latestPart > currentPart) {
        return true;
      } else if (latestPart < currentPart) {
        return false;
      }
    }
    return false;
  }
};
ReleaseNotesManager.GITHUB_API_URL = "https://api.github.com/repos/muckmuck96/obsidian-file-share/releases/latest";

// src/modals/ReleaseNotesModal.ts
var import_obsidian11 = require("obsidian");
var ReleaseNotesModal = class extends import_obsidian11.Modal {
  constructor(app, version, releaseTitle, releaseNotes) {
    super(app);
    this.version = version;
    this.releaseTitle = releaseTitle;
    this.releaseNotes = releaseNotes;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: `FileShare - Update Notes` });
    if (this.releaseTitle) {
      contentEl.createEl("h3", { text: this.releaseTitle });
    }
    const notesContainer = contentEl.createDiv();
    notesContainer.className = "release-notes-content";
    if (this.releaseNotes) {
      const lines = this.releaseNotes.split("\n");
      lines.forEach((line) => {
        if (line.startsWith("## ")) {
          notesContainer.createEl("h2", { text: line.substring(3) });
        } else if (line.startsWith("### ")) {
          notesContainer.createEl("h3", { text: line.substring(4) });
        } else if (line.startsWith("#### ")) {
          notesContainer.createEl("h4", { text: line.substring(5) });
        } else if (line.startsWith("- ")) {
          const ul = notesContainer.querySelector("ul:last-of-type") || notesContainer.createEl("ul");
          ul.createEl("li", { text: line.substring(2) });
        } else if (line.startsWith("* ")) {
          const ul = notesContainer.querySelector("ul:last-of-type") || notesContainer.createEl("ul");
          ul.createEl("li", { text: line.substring(2) });
        } else if (line.trim() !== "") {
          notesContainer.createEl("p", { text: line });
        } else {
          notesContainer.createEl("br");
        }
      });
    } else {
      notesContainer.createEl("p", { text: "No release notes available." });
    }
    const buttonContainer = contentEl.createDiv();
    buttonContainer.style.marginTop = "20px";
    buttonContainer.style.textAlign = "right";
    const closeButton = buttonContainer.createEl("button", { text: "Close" });
    closeButton.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var FileSharePlugin = class extends import_obsidian12.Plugin {
  constructor() {
    super(...arguments);
    this.friendCommandIds = [];
  }
  // Track registered friend command IDs
  async onload() {
    await this.loadSettings();
    this.secure = new Secure(this);
    this.fileValidator = new FileValidator(this);
    this.app.workspace.onLayoutReady(async () => {
      if (!this.settings.privateKey || !this.settings.publicKey) {
        const { privateKey, publicKey } = await this.secure.generateKeyPair();
        this.settings.privateKey = privateKey;
        this.settings.publicKey = publicKey;
        await this.saveSettings();
      }
      this.checkForUpdates();
    });
    this.connectionStatus = this.addStatusBarItem();
    this.socket = new Socket(this);
    this.socket.init();
    this.fileTransmitter = new FileTransmitter(this);
    this.fileRequestQueue = new FileRequestQueue(this.fileTransmitter.sendFile.bind(this.fileTransmitter), this);
    this.app.workspace.onLayoutReady(() => {
      this.fileTreeDecorator = new FileTreeDecorator(this);
    });
    this.addRibbonIcon("refresh-cw", "Toggle connection", () => {
      this.socket.toggleConnection();
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", this.onFileMenu.bind(this))
    );
    this.addCommand({
      id: "send-file-to",
      name: "Send current file to...",
      checkCallback: (checking) => {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          if (!checking) {
            new FileShareModal(
              this,
              this.socket,
              this.settings.friends,
              activeFile
            ).open();
          }
          return true;
        }
        return false;
      }
    });
    this.registerFriendCommands();
    this.addSettingTab(new FileShareSettingTab(this.app, this));
  }
  onunload() {
    this.socket.close();
    if (this.fileTreeDecorator) {
      this.fileTreeDecorator.cleanup();
    }
  }
  getDefaultSettings() {
    return DEFAULT_SETTINGS;
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
    if (this.settings.friends && this.settings.friends.length > 0) {
      let migrationNeeded = false;
      this.settings.friends = this.settings.friends.map((friend) => {
        if (friend.hotkey && typeof friend.hotkey === "string") {
          migrationNeeded = true;
          const { hotkey, ...friendWithoutHotkey } = friend;
          return {
            ...friendWithoutHotkey,
            enableHotkey: true
          };
        }
        return friend;
      });
      if (migrationNeeded) {
        await this.saveSettings();
        console.log("File Share: Migrated friend hotkey settings to new format");
      }
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onFileMenu(menu, file) {
    if (file instanceof import_obsidian12.TFile) {
      menu.addItem((item) => {
        item.setTitle("Send to ...").setIcon("paper-plane").onClick(() => {
          new FileShareModal(
            this,
            this.socket,
            this.settings.friends,
            file
          ).open();
        });
      });
    } else if (file instanceof import_obsidian12.TFolder) {
      menu.addItem((item) => {
        item.setTitle("Send folder to ...").setIcon("paper-plane").onClick(() => {
          new FileShareModal(
            this,
            this.socket,
            this.settings.friends,
            null,
            file
          ).open();
        });
      });
    }
  }
  registerFriendCommands() {
    this.friendCommandIds = [];
    this.settings.friends.forEach((friend, index) => {
      if (friend.enableHotkey) {
        const commandId = this.generateHotkeyId(friend.username);
        this.friendCommandIds.push(commandId);
        this.addCommand({
          id: commandId,
          name: `Send current file to ${friend.username}`,
          checkCallback: (checking) => {
            const activeFile = this.app.workspace.getActiveFile();
            if (activeFile) {
              if (!checking) {
                this.sendFileToFriend(activeFile, friend);
              }
              return true;
            }
            return false;
          }
        });
      }
    });
  }
  generateHotkeyId(username) {
    return `send-to-${username.toLowerCase().replace(/[^a-z0-9]/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "")}`;
  }
  async sendFileToFriend(file, friend) {
    if (this.socket.getWS().readyState !== WebSocket.OPEN) {
      new import_obsidian12.Notice("You are not connected to the FileShare server. Please connect first.");
      return;
    }
    const validation = await this.fileValidator.validateFile(file);
    if (!validation.valid) {
      this.fileValidator.showValidationError(validation.error);
      return;
    }
    this.socket.send("checkOnline", { target: friend.publicKey });
    this.socket.getWS().onmessage = (message) => {
      const data = JSON.parse(message.data);
      if (data.type === "checkOnline" && data.target === friend.publicKey) {
        if (data.online) {
          this.fileRequestQueue.addRequest(file, friend);
          if (this.settings.scanSendingFiles) {
            this.fileTransmitter.scanFileAndSend(file, friend);
          }
        } else {
          new import_obsidian12.Notice(`${friend.username} is offline at the moment`);
        }
      } else if (data.type === "response") {
        this.fileRequestQueue.handleResponse(data.id, data.accepted, data.hash);
      }
    };
  }
  async checkForUpdates() {
    try {
      const currentVersion = this.manifest.version;
      if (this.settings.lastSeenVersion !== currentVersion) {
        const release = await ReleaseNotesManager.fetchLatestRelease();
        if (release) {
          new ReleaseNotesModal(
            this.app,
            currentVersion,
            release.name,
            release.body
          ).open();
        }
        this.settings.lastSeenVersion = currentVersion;
        await this.saveSettings();
      }
    } catch (error) {
      console.error("Error checking for updates:", error);
    }
  }
};
var main_default = FileSharePlugin;

/* nosourcemap */